git-difftool: add --start and --end options
If you specify --start and --end git-difftool will compare files between
two arbitrary revisions.

Signed-off-by: David Aguilar <davvid@gmail.com>

diff --git a/bin/git-difftool b/bin/git-difftool
--- a/bin/git-difftool
+++ b/bin/git-difftool
@@ -8,14 +8,17 @@
 # at the discretion of Junio C Hamano.
 #
 
-USAGE='[--tool=tool] [--no-prompt] [file to merge] ...'
+USAGE='[--tool=tool] [--commit=ref] [--start=ref --end=ref] [--no-prompt] [file to merge] ...'
 SUBDIRECTORY_OK=Yes
 OPTIONS_SPEC=
 . git-sh-setup
 require_work_tree
 
-index_present ()
-{
+parse_arg () {
+	expr "z$1" : 'z-[^=]*=\(.*\)'
+}
+
+index_present () {
     test -n "$index_mode"
 }
 
@@ -31,21 +34,29 @@ should_prompt () {
 	! test -n "$no_prompt"
 }
 
+use_rev_range () {
+	test -n "$start" && test -n "$end"
+}
+
+merge_three () {
+	index_present && modified_present && ! use_rev_range
+}
 
 modified_files () {
-	if commitish_present; then
-		git diff --name-only "$commitish" "$@"
+	if use_rev_range; then
+		git diff --name-only "$start".."$end" -- "$@" 2>/dev/null
+	elif commitish_present; then
+		git diff --name-only "$commitish" -- "$@" 2>/dev/null
 	else
-		git diff --name-only "$@"
+		git diff --name-only -- "$@" 2>/dev/null
 	fi
 }
 
 staged_files() {
-	git diff --name-only --cached "$@"
+	git diff --name-only --cached "$@" 2>/dev/null
 }
 
-cleanup_temp_files ()
-{
+cleanup_temp_files () {
 	if test "$1" = --save-backup; then
 		mv -- "$BACKUP" "$MERGED.orig"
 		rm -f -- "$LOCAL" "$REMOTE" "$BASE"
@@ -54,9 +65,8 @@ cleanup_temp_files ()
 	fi
 }
 
-check_unchanged ()
-{
-	if test "$MERGED" -nt "$BACKUP"; then
+check_unchanged () {
+	if use_rev_range || test "$MERGED" -nt "$BACKUP"; then
 		status=0
 	else
 		status=1
@@ -79,10 +89,13 @@ merge_file ()
 {
 	MERGED="$1"
 
-	modified_mode=$(modified_files -- "$MERGED")
-	index_mode=$(staged_files -- "$MERGED")
+	modified_mode=$(modified_files "$MERGED")
+	index_mode=$(staged_files "$MERGED")
 
-	if ! modified_present && ! index_present; then
+	if ! modified_present && use_rev_range; then
+		echo "$MERGED: no changes between '$start' and '$end'."
+		exit 1
+	elif ! modified_present && ! index_present; then
 		if test ! -f "$MERGED"; then
 			echo "$MERGED: file not found"
 		else
@@ -91,22 +104,43 @@ merge_file ()
 		exit 1
 	fi
 
-	head=${commitish-HEAD}
 	ext="$$$(expr "$MERGED" : '.*\(\.[^/]*\)$')"
 	BACKUP="./$MERGED.BACKUP.$ext"
 	LOCAL="./$MERGED.LOCAL.$ext"
 	REMOTE="./$MERGED.HEAD.$ext"
 	BASE="./$MERGED.INDEX.$ext"
 
-	mv -- "$MERGED" "$BACKUP"
-	cp -- "$BACKUP" "$MERGED"
+	test -f "$MERGED" && cp -- "$MERGED" "$BACKUP"
 
-	cp "$MERGED" "$LOCAL"
-	git show "$head":"$MERGED" > "$REMOTE"
+	if use_rev_range; then
+		base=current
+		local=start
+		remote=end
+		if ! git show "$start":"$MERGED" > "$LOCAL" 2>/dev/null; then
+			cleanup_temp_files;
+			return
+		fi
+		if ! git show "$end":"$MERGED" > "$REMOTE" 2>/dev/null; then
+			cleanup_temp_files;
+			return
+		fi
 
-	# If changes are present in the index use them as $BASE
-	git checkout-index --prefix=.index- "$MERGED"
-	mv .index-"$MERGED" "$BASE"
+		# $BASE might be needed by custom mergetool commands
+		if test -f "$MERGED"; then
+			cp -- "$MERGED" "$BASE"
+		else
+			cp -- "$LOCAL" "$BASE"
+		fi
+	else
+		base=index
+		local=current
+		remote=${commitish-HEAD}
+		cp -- "$MERGED" "$LOCAL"
+		git show "$remote":"$MERGED" > "$REMOTE"
+		# If changes are present in the index use them as $BASE
+		git checkout-index --prefix=.index- "$MERGED"
+		mv -- .index-"$MERGED" "$BASE"
+	fi
 
 	if should_prompt; then
 		printf "\nEditing '$MERGED':\n"
@@ -116,20 +150,21 @@ merge_file ()
 
 	case "$merge_tool" in
 	kdiff3)
-		if index_present && modified_present; then
+		basename=$(basename "$MERGED")
+		if merge_three; then
 		(
 			"$merge_tool_path" --auto \
-				--L1 "[index] $MERGED" \
-				--L2 "[current] $MERGED" \
-				--L3 "[$head] $MERGED" \
+				--L1 "[$base] $basename" \
+				--L2 "[$local] $basename" \
+				--L3 "[$remote] $basename" \
 				-o "$MERGED" "$BASE" "$LOCAL" "$REMOTE" \
 				> /dev/null 2>&1
 		)
 		else
 		(
 			"$merge_tool_path" --auto \
-				--L1 "[current] $MERGED" \
-				--L2 "[$head] $MERGED" \
+				--L1 "[$local] $basename" \
+				--L2 "[$remote] $basename" \
 				-o "$MERGED" "$LOCAL" "$REMOTE" \
 				> /dev/null 2>&1
 		)
@@ -138,7 +173,7 @@ merge_file ()
 		;;
 
 	tkdiff)
-		if index_present && modified_present; then
+		if merge_three; then
 			"$merge_tool_path" \
 				-a "$BASE" \
 				-o "$MERGED" "$LOCAL" "$REMOTE"
@@ -150,20 +185,17 @@ merge_file ()
 		;;
 
 	meld|vimdiff)
-		touch "$BACKUP"
 		"$merge_tool_path" "$LOCAL" "$MERGED" "$REMOTE"
 		check_unchanged
 		;;
 
 	gvimdiff)
-		touch "$BACKUP"
 		"$merge_tool_path" -f "$LOCAL" "$MERGED" "$REMOTE"
 		check_unchanged
 		;;
 
 	xxdiff)
-		touch "$BACKUP"
-		if index_present && modified_present; then
+		if merge_three; then
 			"$merge_tool_path" -X --show-merged-pane \
 				-R 'Accel.SaveAsMerged: "Ctrl-S"' \
 				-R 'Accel.Search: "Ctrl+F"' \
@@ -182,8 +214,7 @@ merge_file ()
 		;;
 
 	opendiff)
-		touch "$BACKUP"
-		if index_present && modified_present; then
+		if merge_three; then
 			"$merge_tool_path" "$LOCAL" "$REMOTE" \
 				-ancestor "$BASE" \
 				-merge "$MERGED" | cat
@@ -195,8 +226,7 @@ merge_file ()
 		;;
 
 	ecmerge)
-		touch "$BACKUP"
-		if index_present && modified_present; then
+		if merge_three; then
 			"$merge_tool_path" "$BASE" "$LOCAL" "$REMOTE" \
 				--default --mode=merge3 --to="$MERGED"
 		else
@@ -207,7 +237,7 @@ merge_file ()
 		;;
 
 	emerge)
-		if index_present; then
+		if merge_three; then
 			"$merge_tool_path" \
 				-f emerge-files-with-ancestor-command \
 				"$LOCAL" "$REMOTE" "$BASE" \
@@ -221,7 +251,6 @@ merge_file ()
 	*)
 		if test -n "$merge_tool_cmd"; then
 			if test "$merge_tool_trust_exit_code" = "false"; then
-				touch "$BACKUP"
 				( eval $merge_tool_cmd )
 				check_unchanged
 			else
@@ -232,16 +261,17 @@ merge_file ()
 		;;
 	esac
 
-	if test "$status" -ne 0; then
-		if should_prompt; then
-			echo "merge of $MERGED failed" 1>&2
+	if ! use_rev_range; then
+		if test "$status" -ne 0; then
+			if should_prompt; then
+				echo "merge of $MERGED failed" 1>&2
+			fi
+			mv -- "$BACKUP" "$MERGED"
+			cleanup_temp_files
+			exit 1
 		fi
-		mv -- "$BACKUP" "$MERGED"
-		cleanup_temp_files
-		exit 1
+		git add -- "$MERGED"
 	fi
-
-	git add -- "$MERGED"
 	cleanup_temp_files
 }
 
@@ -251,7 +281,7 @@ do
 	-t|--tool*)
 		case "$#,$1" in
 		*,*=*)
-			merge_tool=$(expr "z$1" : 'z-[^=]*=\(.*\)')
+			merge_tool=$(parse_arg "$1")
 			shift
 			;;
 		1,*)
@@ -264,10 +294,10 @@ do
 			;;
 		esac
 		;;
-	-r|--ref*)
+	-c|--commit*)
 		case "$#,$1" in
 		*,*=*)
-			commitish=$(expr "z$1" : 'z-[^=]*=\(.*\)')
+			commitish=$(parse_arg "$1")
 			shift
 			;;
 		1,*)
@@ -276,6 +306,38 @@ do
 		*)
 			shift
 			commitish="$1"
+			shift
+			;;
+		esac
+		;;
+	-s|--start*)
+		case "$#,$1" in
+		*,*=*)
+			start=$(parse_arg "$1")
+			shift
+			;;
+		1,*)
+			usage
+			;;
+		*)
+			shift
+			start="$1"
+			shift
+			;;
+		esac
+		;;
+	-e|--end*)
+		case "$#,$1" in
+		*,*=*)
+			end=$(parse_arg "$1")
+			shift
+			;;
+		1,*)
+			usage
+			;;
+		*)
+			shift
+			end="$1"
 			shift
 			;;
 		esac
@@ -417,12 +479,15 @@ if test $# -eq 0; then
 		do
 			merge_file "$i" < /dev/tty > /dev/tty
 		done
-	else
+	elif ! use_rev_range; then
 		staged_files |
 		while IFS= read i
 		do
 			merge_file "$i" < /dev/tty > /dev/tty
 		done
+	else
+		echo "Nothing to compare."
+		exit 0
 	fi
 else
 	while test $# -gt 0
