Updated README, .gitignore for ugit-patches
Signed-off by: David Aguilar <davvid@gmail.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,17 +5,17 @@
 # Fancy colors used to beautify the output a bit.
 #
 if [ $NOCOLOR ] ; then
-    NORMAL=""
-    BOLD=""
-    RED=""
-    YELLOW=""
-    GREEN=""
+	NORMAL=""
+	BOLD=""
+	RED=""
+	YELLOW=""
+	GREEN=""
 else
-    NORMAL="\033[0m"
-    BOLD="\033[1m"
-    RED="\033[91m"
-    YELLOW="\033[01;93m"
-    GREEN="\033[92m"
+	NORMAL="\033[0m"
+	BOLD="\033[1m"
+	RED="\033[91m"
+	YELLOW="\033[01;93m"
+	GREEN="\033[92m"
 fi
 
 EXIT_SUCCESS=0
@@ -42,15 +42,15 @@ export PATH
 checkPython()
 {
 	if [ -z "$PYTHON" ] ; then
-	    PYTHON=`which python 2>/dev/null`
+		PYTHON=`which python 2>/dev/null`
 	fi
 	printf "Checking for Python\t\t\t:  "
 	if [ ! -x "$PYTHON" ] ; then
-	  printf $RED"not found!"$NORMAL"\n"
-	  echo "Please make sure that the Python interpreter is available in your PATH"
-	  echo "or invoke configure using the PYTHON flag, e.g."
-	  echo "$ PYTHON=/usr/local/bin/python configure"
-	  exit $EXIT_FAILURE
+		printf $RED"not found!"$NORMAL"\n"
+		echo "Please make sure that the Python interpreter is available in your PATH"
+		echo "or invoke configure using the PYTHON flag, e.g."
+		echo "$ PYTHON=/usr/local/bin/python configure"
+		exit $EXIT_FAILURE
 	fi
 	printf $GREEN"$PYTHON"$NORMAL"\n"
 }
@@ -60,28 +60,27 @@ checkPython()
 #
 checkWAF()
 {
-	printf "Checking for WAF\t\t\t:  "
 	#installed miniwaf in sourcedir
 	if [ -z "$WAF" ] ; then
-	    if [ -f "${WORKINGDIR}/waf" ] ; then
-		WAF="${WORKINGDIR}/waf"
-		if [ ! -x $WAF ] ; then
-		    chmod +x $WAF
+		if [ -f "${WORKINGDIR}/buildutils/waf" ] ; then
+			WAF="${WORKINGDIR}/buildutils/waf"
+			if [ ! -x $WAF ] ; then
+				chmod +x $WAF
+			fi
 		fi
-	    fi
 	fi
 	#global installed waf with waf->waf.py link
 	if [ -z $WAF ] ; then
-	    WAF=`which waf 2>/dev/null`
+		WAF=`which waf 2>/dev/null`
 	fi
 	# neither waf nor miniwaf could be found
 	if [ ! -x "$WAF" ] ; then
-	    printf $RED"not found"$NORMAL"\n"
-	    echo "Goto http://www.freehackers.org/~tnagy/bksys.html"
-	    echo "and download a waf version"
-	    exit $EXIT_FAILURE
+		printf $RED"not found"$NORMAL"\n"
+		echo "Goto http://www.freehackers.org/~tnagy/bksys.html"
+		echo "and download a waf version"
+		exit $EXIT_FAILURE
 	else
-	  printf $GREEN"$WAF"$NORMAL"\n"
+		printf $GREEN"$WAF"$NORMAL"\n"
 	fi
 }
 
@@ -137,10 +136,10 @@ $WAF configure $* || exit $EXIT_ERROR
 
 #create a Makefile if waf configure succeeds
 if [ -f "${WORKINGDIR}/.lock-wscript" ] ; then
-    if [ -f "Makefile" ] ; then
-	echo ""
-    else
-        generateMakefile
-    fi
+	if [ -f "Makefile" ] ; then
+		echo ""
+	else
+		generateMakefile
+	fi
 fi
 exit $EXIT_SUCCESS
