style: do the mainstream python thing and use spaces instead of tabs
No comment.

Signed-off-by: David Aguilar <davvid@gmail.com>

diff --git a/t/run_tests b/t/run_tests
--- a/t/run_tests
+++ b/t/run_tests
@@ -7,8 +7,8 @@ COLA=$(which cola)
 test -z "$COLA" && ERROR=1
 
 if [ $ERROR ]; then
-	echo "cola must be in your path in order to call run_tests directly."
-	exit -1
+    echo "cola must be in your path in order to call run_tests directly."
+    exit -1
 fi
 BINDIR=$(dirname $COLA)
 PREFIX=$(dirname $BINDIR)
@@ -16,15 +16,15 @@ PYTHONPATH="$PREFIX"/share:"$PREFIX"/share/cola:"$PYTHONPATH"
 export PYTHONPATH
 
 (
-	for unittest in t[0-9]*.py; do
-		echo
-		echo -n "$unittest "
-		./$unittest
-		if [ $? -ne 0 ] && [ -z "$RUN_ALL" ]; then
-			echo "$unittest failed with exit code $?"
-			exit -1
-		fi
-	done
+    for unittest in t[0-9]*.py; do
+        echo
+        echo -n "$unittest "
+        ./$unittest
+        if [ $? -ne 0 ] && [ -z "$RUN_ALL" ]; then
+            echo "$unittest failed with exit code $?"
+            exit -1
+        fi
+    done
 
 ) 2>&1 | perl -e '
 
@@ -35,13 +35,13 @@ my ($start_sec, $start_ms) = gettimeofday();
 my $count = 0;
 my @fail = ();
 while(<>) {
-	print;
-	if ( /(\d+) tests/ ) {
-		$count += $1;
-	}
-	elsif ( /(.*) failed/ ) {
-		push @fail, $1;
-	}
+    print;
+    if ( /(\d+) tests/ ) {
+        $count += $1;
+    }
+    elsif ( /(.*) failed/ ) {
+        push @fail, $1;
+    }
 }
 
 my ($end_sec, $end_ms) = gettimeofday();
@@ -51,22 +51,22 @@ my $sec = $end_sec - $start_sec;
 my $secfrac = ( $end_ms - $start_ms ) * 100;
 
 while ( $secfrac < 0.0 ) {
-	$secfrac += 1000 * 100;
+    $secfrac += 1000 * 100;
 }
- 
+
 $secfrac = substr("$secfrac", 0, 2);
 
 while ( $sec > 60 ) {
-	$sec -= 60;
-	$min++;
+    $sec -= 60;
+    $min++;
 }
 
 if ( @fail ) {
-	print "\n";
-	print "The following test FAILED:\n";
-	print "-"x70 ."\n\t";
-	print join("\n\t", @fail);
-	print "\n";
+    print "\n";
+    print "The following test FAILED:\n";
+    print "-"x70 ."\n\t";
+    print join("\n\t", @fail);
+    print "\n";
 }
 
 print "\n";
