tests: use the built cola instead of the installed one
The test suite used to require you to install cola before testing.
The cola tests now use the build/lib directory instead.

Signed-off-by: David Aguilar <davvid@gmail.com>

diff --git a/t/run_tests b/t/run_tests
--- a/t/run_tests
+++ b/t/run_tests
@@ -1,30 +1,32 @@
 #!/bin/sh
-cd $(dirname $0)
+cd $(dirname $0)/..
+rootdir=$(pwd)
+RUN_ALL=
+! test -d "$rootdir"/build/lib && {
+	echo
+	echo "ERROR: build/lib doesn't exist." 2>&1
+	echo "Please build git cola first." 2>&1
+	echo
+	exit 42
+}
 
-RUN_ALL=''
-COLA=$(which cola)
-
-if ! test -x "$COLA"; then
-    echo "cola must be in your path in order to call run_tests directly."
-    exit -1
-fi
-BINDIR=$(dirname $COLA)
-PREFIX=$(dirname $BINDIR)
-PYTHONPATH="$PREFIX"/lib/python2.4/site-packages:"$PREFIX"/lib/python2.5/site-packages:"$PYTHONPATH"
+PATH="$rootdir":"$PATH"
+PYTHONPATH="$rootdir"/build/lib:"$PYTHONPATH"
+export PATH
 export PYTHONPATH
-
 (
-    for unittest in t[0-9]*.py; do
-        echo -n "$unittest"
-        ./"$unittest"
-        status=$?
-        if ! test "$status" = "0" && test -z "$RUN_ALL"; then
-            echo " failed with exit code $?"
-            exit -1
-        else
-            echo
-        fi
-    done
+	cd t
+	for unittest in t[0-9]*.py; do
+		echo -n "$unittest"
+		./"$unittest"
+		status=$?
+		if ! test $status -eq 0 && test -z "$RUN_ALL"; then
+			echo " failed with exit code $?"
+			exit -1
+		else
+			echo
+		fi
+	done
 
 ) 2>&1 | perl -e '
 
@@ -35,13 +37,13 @@ my ($start_sec, $start_ms) = gettimeofday();
 my $count = 0;
 my @fail = ();
 while(<>) {
-    print;
-    if ( /(\d+) tests/ ) {
-        $count += $1;
-    }
-    elsif ( /failed/ ) {
-        push @fail, $1;
-    }
+	print;
+	if ( /(\d+) tests/ ) {
+		$count += $1;
+	}
+	elsif ( /failed/ ) {
+		push @fail, $1;
+	}
 }
 
 my ($end_sec, $end_ms) = gettimeofday();
@@ -51,22 +53,22 @@ my $sec = $end_sec - $start_sec;
 my $secfrac = ( $end_ms - $start_ms ) * 100;
 
 while ( $secfrac < 0.0 ) {
-    $secfrac += 1000 * 100;
+	$secfrac += 1000 * 100;
 }
 
 $secfrac = substr("$secfrac", 0, 2);
 
 while ( $sec > 60 ) {
-    $sec -= 60;
-    $min++;
+	$sec -= 60;
+	$min++;
 }
 
 if ( @fail ) {
-    print "\n";
-    print "The following test FAILED:\n";
-    print "-"x70 ."\n\t";
-    print join("\n\t", @fail);
-    print "\n";
+	print "\n";
+	print "The following test FAILED:\n";
+	print "-"x70 ."\n\t";
+	print join("\n\t", @fail);
+	print "\n";
 }
 
 print "\n";
@@ -75,4 +77,5 @@ print "-"x70 ."\n";
 print "$count tests total\n";
 print "$min min $sec.$secfrac sec total runtime\n\n";
 '
+test -z "$DEBUG" && rm -rf tmp
 exit 0
